<?php

return [
    'shop_page_prefix' => env('AMPLIFY_SHOP_PAGE_PREFIX', 'shop'),
    'excluded_page_types' => ['static_page', 'shop_by_catalog'],
    'shop_page_default_view' => 'list',
    'fallback_image_path' => 'assets/img/No-Image-Placeholder-min.png',
    'easyask_single_product_index' => 'id',
    'mega_menu_max_height' => '310px',
    'enable_language' => false,
    'enable_exchange_reward' => true,
    'exchange_reward_client_token' => '078bcc74',
    'exchange_reward_secret' => '5016e7d76f9c3111bf0d01773f4791ea',
    'exchange_reward_baseurl' => 'https://safetyproducts.online-rewards.com/rpc/',
    'mobile_screen_menu' => 'mobile-menu',
    'user_account_top_menu' => 'account-menu',
    'user_account_sidebar_menu' => 'account-sidebar',
    'site_primary_menu' => 'primary-menu',
    'guest_default' => null,
    'guest_checkout_warehouse' => null,
    'guest_checkout' => false,
    'force_shipping_address_customer_id' => null,
    'guest_add_to_cart' => false,
    'product_available_text' => 'Available',
    'product_not_available_text' => 'Available in 3-5 days',
    'right_sidebar' => true,
    'styles' => [
        'plugin-style' => [],
        'custom-style' => [],
        'internal-style' => [],
    ],
    'scripts' => [
        'head-script' => [],
        'plugin-script' => [],
        'template-script' => [],
        'custom-script' => [],
        'internal-script' => [],
        'footer-script' => [],
    ],
    'cart_item_badge_style' => 'items',
    'show_parent_product_for_sku' => true,
];
