<?php

return [
    'shop_page_prefix' => env('AMPLIFY_SHOP_PAGE_PREFIX', 'store'),
    'product_page_prefix' => env('AMPLIFY_PRODUCT_PAGE_PREFIX', 'product'),
    'excluded_page_types' => ['static_page', 'shop_by_catalog'],
    'shop_page_default_view' => 'list',
    'fallback_image_path' => 'assets/img/No-Image-Placeholder-min.png',
    'easyask_single_product_index' => 'id',
    'mega_menu_max_height' => '310px',
    'enable_language' => false,
    'enable_exchange_reward' => true,
    'exchange_reward_client_token' => '',
    'exchange_reward_secret' => '',
    'exchange_reward_baseurl' => '',
    'mobile_screen_menu' => 'mobile-menu',
    'user_account_top_menu' => 'account-menu',
    'user_account_sidebar_menu' => 'account-sidebar',
    'site_primary_menu' => 'primary-menu',
    'guest_default' => null,
    'guest_checkout_warehouse' => null,
    'guest_checkout' => false,
    'force_shipping_address_customer_id' => null,
    'guest_add_to_cart' => false,
    'redirect_to_product_detail_page_on_search' => false,
    'product_available_text' => 'Available',
    'product_not_available_text' => 'Available in 3-5 days',
    'right_sidebar' => true,
    'styles' => [
        'plugin-style' => [],
        'custom-style' => [],
        'internal-style' => [],
    ],
    'scripts' => [
        'head-script' => [],
        'plugin-script' => [],
        'template-script' => [],
        'custom-script' => [],
        'internal-script' => [],
        'footer-script' => [],
    ],
    'cart_item_badge_style' => 'items',
    'show_parent_product_for_sku' => true,
    'permissions' => [
        'account-summary' => 'allow-account-summary',
        'checkout' => 'choose-warehouse,choose-shipto,credit-card-payment,payment-on-accounts',
        'contact-management' => 'l,v,a,u,r',
        'dashboard' => 'allow-dashboard',
        'favorites' => 'manage-global-list,use-global-list,manage-personal-list',
        'invoices' => 'v,pay',
        'login-management' => 'manage-logins,impersonate',
        'message' => 'messaging',
        'order' => 'v,c,add-to-cart',
        'order-approval' => 'approve',
        'order-processing-rules' => 'manage-rules',
        'order-rejected' => 'l,v',
        'past-items' => 'past-items-list, past-items-history',
        'profile' => 'change-start-page',
        'quote' => 'v,rfq',
        'reports' => 'summary',
        'role' => 'v,manage',
        'saved-carts' => 'l',
        'ship-to-addresses' => 'l,v,a,u,r',
        'shop' => 'add-to-cart,browse',
        'switch-account' => 'switch-account',
        'ticket' => 'tickets',
    ]
];
